---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# A historical collection of impedance functions for active travel accessibility analysis in Canada

<!-- badges: start -->
<!-- badges: end -->

Mahdis Moghadasi (School of Earth, Environment and Society, McMaster University)
Antonio Paez (School of Earth, Environment and Society, McMaster University)

## Abstract

Active transport accessibility has been growing in importance for reaching sustainable outcomes in urban planning. Assessment of accessibility is done by using different methods such as gravity-based models, potential models, etc. The impedance function is used for calculating these measures in order to reflect the friction of distance separating origins and destinations, which might have a significant impact on the value of accessibility. This study investigates distance-decay functions based on time-willingness to reach different destinations such as home, work, school, grocery stores, restaurants, and sports places by walking and cycling all over Canada. The study employs general social survey (GSS) (time-use) data from 1986 to 2015. This dataset contains travel time data of cycling and walking trips of many of the Census Metropolitan Areas (CMAs) and non-CMA areas in Canada. In addition, each episode contains pumID, start time, end time, duration, origin and destination of each trip. Results show home is the most common destination for both cycling and walking trips during 1986 - 2015. Traveling to work or school and then the grocery store, other stores or mall are the most destinations for walking travels respectively. However, for cycling travel, after travel to work or school, the sports center, field or arena is the most destination. Strong distance-decay effects have been shown in the results. Most cycling trips are shorter than 125 minutes and very few exceed 250 minutes and most walking trips are shorter than 60 minutes in all years. The mean and median values for walking duration were 65.3 – 30, 19.1 – 10, 11.2 -5, 12.3-10, 18.7-15 from 1986 to 2015 and for cycling duration were 30.9 – 20, 20.6 -15, 21.5 – 15, and 26.2 – 15 from 1992 to 2015, respectively.

